name: Publish course
on:
  pull_request:
    branches: ["courses/*"]
  push:
    branches: ["courses/*"]
permissions:
  contents: read
jobs:
  publish:
    uses: dataprosvet/dataprosvet-lectures/.github/workflows/reusable-publish-course.yml@c5c1a5b8d69182c0e2ab9c49dcf9ba0ffed57adc
